export {default as LoginScreen} from './LoginScreen';
export {default as RegisterScreen} from './RegisterScreen';
export {default as OnBoardScreen} from './OnBoardScreen';
export {default as SyncScreen} from './SyncPhoneScreen';
export {default as SyncingScreen} from './SyncingContactScreen';
export {default as ProfileScreen} from './ProfileScreen';
export {default as ResetPasswordScreen} from './ResetPassword';
export {default as EditProfileScreen} from './EditProfileScreen';
// export {default as NotificationTabsScreen} from './InvitationScreen/index1';
export {default as HomeScreen} from './HomeScreen';
export {default as MapAndChatScreen} from './MapAndChatScreen';
export {default as ChatScreen} from './ChatScreen';
export {default as EditTripScreen} from './EditTripScreen';
export {default as MapScreen} from './MapScreen';
// export {default as GeneralNotificationTab} from './InvitationScreen/GeneralNotificationTab';
export {default as InvitaitionTab} from './InvitationScreen';
export {default as GeneralNotification} from './GeneralNotificationScreen';
export {default as InvitationScreen} from './InvitationScreen';
