export const types = {
  onBoardFinished: 'onBoardFinished',
  isLoadingTrue: 'isLoadingTrue',
  isLoadingFalse: 'isLoadingFalse',
  LoginType: 'LoginType',
  LogoutType: 'LogoutType',
  LogoutFirebaseType: 'LogoutFirebaseType',
  UpdateProfile: 'UpdateProfile',
  UpdateUser: 'UpdateUser',
  UpdateAuth: 'UpdateAuth',
  RegisterUser: 'RegisterUser',
  RecentLocation: 'RecentLocation',
  SetRecentLocation: 'SetRecentLocation',
  selectedValType: 'selectedValType',
  selectedAnsType: 'selectedAnsType',
  isQuestionTrue: 'isQuestionTrue',
  isQuestionFalse: 'isQuestionFalse',
  selectedAnsTypeSaga: 'selectedAnsTypeSaga',
  CleanRecentLocation: 'CleanRecentLocation',
  fcmRegType: 'fcmRegType',
};
