import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hp, wp} from '../../Config/responsive';
import {Colors} from '../../Theme/Variables';

export const styles = StyleSheet.create({
  staticMapImg: {
    flex: 1,
  },
  groupInfoMain: {
    marginTop: hp('0'),
    zIndex: 999,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('4'),
    marginHorizontal: wp('4'),
    paddingVertical: hp('1.5'),
    position: 'absolute',
    bottom: hp('8'),
    width: wp('85'),
    height: hp('10'),
    borderRadius: 10,
    overflow: 'hidden',
    border: 1,
    borderWidth: 1,
    borderColor: Colors.grayBorder,
  },
  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    width: wp('100'),
    height: hp('100'),
    // opacity: 0.67,
  },
  groupLogo: {
    // flex: 0.17,
    resizeMode: 'contain',
    // left: wp('10'),
    marginRight: wp('2'),
    backgroundColor: 'red',
  },
  groupLink: {
    flex: 3,
    // backgroundColor: 'red',
    // height: hp('8'),
    // width: wp('4'),
  },
  groupDesc: {
    flex: 7,
    marginLeft: wp('3'),
    paddingRight: wp('5'),
  },
  groupName: {
    fontSize: hp('2.3'),
    color: Colors.black,
    fontWeight: '600',
  },
  groupMember: {
    fontSize: hp('1.8'),
    // marginTop: hp('0.5'),
    color: Colors.gray,
  },
  externalLinks: {
    width: wp('10'),
    height: hp('10'),
    resizeMode: 'contain',
  },
  kiloMeterText: {
    position: 'absolute',
    left: wp('2'),
    top: hp('1'),
    padding: 5,
    backgroundColor: Colors.gray,
    color: Colors.white,
    borderRadius: 10,
    paddingHorizontal: wp('3'),
  },
  firstCharStyle: {
    zIndex: 999,
    position: 'relative',
    poition: 'absolute',
    bottom: hp('-4.7'),
    width: Dimensions.get('window').width * 0.08,
    height: Dimensions.get('window').width * 0.08,
    left: Platform.OS == 'ios' ? wp('4.7') : wp('4.2'),
    backgroundColor: Colors.white,
  },
  firstTextStyle: {
    fontSize: hp('1.9'),
    color: Colors.primaryColor,
  },
  pImage: {
    // zIndex: -1,
    // zIndex: 999,
    // position: 'relative',
    // position: 'absolute',
    // top: hp('2.7'),
    width: Dimensions.get('window').width * 0.08,
    height: Dimensions.get('window').width * 0.08,
    // left: wp('4.7'),
    backgroundColor: 'red',
    // bottom: hp('2'),
    tintColor: 'red',
    // marginTop: hp('2'),
  },
  pView: {
    // zIndex: -1,
    zIndex: 999,
    // position: 'relative',
    position: 'absolute',
    // top: hp('2.7'),
    // width: Dimensions.get('window').width * 0.1,
    // height: Dimensions.get('window').width * 0.1,
    left: Platform.OS == 'ios' ? wp('5') : wp('4.3'),
    // backgroundColor: 'red',
    bottom: hp('3.5'),
    tintColor: 'red',
    // marginTop: hp('2'),
  },
  closeIcon: {
    justifyContent: 'flex-end',
    alignSelf: 'flex-end',
    marginTop: hp('2'),
    marginRight: wp('1.5'),
  },
  modalStyle: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    shadowColor: '#000000',
    shadowOffset: {
      width: 2,
      height: 10,
    },
    shadowOpacity: 3,
    shadowRadius: 7.68,
    elevation: 20,
    // flex: 1,
    justifyContent: 'flex-start',
    height: hp('87'),
    paddingHorizontal: wp('2'),
  },
  bottomModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  heading: {
    fontSize: hp('2.2'),
    fontWeight: '600',
    color: 'red',
    textAlign: 'center',
    alignSelf: 'center',
  },
  gText: {
    alignSelf: 'center',
    marginBottom: hp('2.3'),
  },
  profileText: {
    marginBottom: hp('1'),
    alignSelf: 'center',
  },
  creatorInfoMain: {
    flexDirection: 'row',
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
  },
  creatorProfile: {
    marginRight: wp('2.5'),
  },
  creatorName: {
    fontSize: hp('2'),
    fontWeight: '600',
    color: Colors.black,
    marginBottom: hp('0.2'),
    flex: 0.8,
  },
  creator: {
    flex: 0.3,
    alignItems: 'center',
    verticalAlign: 'middle',
    textAlign: 'right',
  },
  tripCreator: {
    fontSize: hp('1.8'),
    fontWeight: '400',
    color: Colors.black,
  },
  creatorInfo: {
    verticalAlign: 'middle',
    justifyContent: 'center',
    marginLeft: wp('2.5'),
  },
  locationArea: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flexWrap: 'wrap',
    // backgroundColor: 'yellow',
    marginBottom: hp('1'),
  },
  destinationArea: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flexWrap: 'wrap',
    // backgroundColor: 'yellow',
    // marginTop: hp('3'),
  },
  dotbar: {
    resizeMode: 'contain',
    // width: wp('12'),
    height: hp('6'),
    // maxHeight: hp('20'),
    // marginVertical: hp('-0.5'),
    alignSelf: 'flex-start',
    left: wp('-1.7'),
  },
  locationInfoMain: {
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
    // position: 'relative',
  },
  desImage: {
    resizeMode: 'contain',
    width: wp('11'),
    height: hp('5.5'),
    marginRight: wp('2.5'),
    alignSelf: 'flex-start',
  },
  locImage: {
    resizeMode: 'contain',
    width: wp('11'),
    height: hp('5.5'),
    marginRight: wp('2.5'),
    alignSelf: 'flex-start',
  },
  desText: {
    fontSize: hp('1.8'),
    fontWeight: '400',
    color: 'black',
    flex: 1,
    lineHeight: 22,
  },
  memberList: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flex: 1,
  },
  memberText: {
    borderBottomColor: Colors.grayBorder,
    borderBottomWidth: 1,
    flex: 1,
    paddingBottom: hp('1.5'),
    marginBottom: hp('1.5'),
    marginTop: hp('2.7'),
    marginLeft: wp('2.5'),
    flexDirection: 'row',
  },
  memberInfo: {
    flexDirection: 'row',
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
    height: 'auto',
  },
  LText: {
    // flex: 0.8,
    borderColor: Colors.themeColorDark,
    width: wp('75'),
    marginBottom: hp('2'),
    textAlignVertical: 'top',
    verticalAlign: 'top',
  },
  dotImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // marginVertical: hp('3'),
    // height: hp('6'),
    // backgroundColor: 'red',
  },
});
