import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hp, wp} from '../../Config/responsive';
import {Colors, shadowStyleGlobal} from '../../Theme/Variables';

export const styles = StyleSheet.create({
  tips: {
    // paddingHorizontal: wp('3.5'),
    // backgroundColor: Colors.white,
    // paddingTop: hp('3'),
    flex: 1,
  },
  headerStyle: {
    paddingHorizontal: wp('0'),
  },
  hdTitle: {
    fontWeight: '600',
  },
  rowBack: {
    // width: '100%',
    // marginBottom: 10,
    // flex: 1,
    borderRadius: 15,
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginHorizontal: wp('3.5'),
  },
  backRightBtn: {
    // textAlign: 'left',
    // alignItems: 'center',
  },
  backRightBtnLeft: {
    backgroundColor: '#EA4335',
    flex: 1,
    height: Platform.OS == 'ios' ? hp('19.2') : hp('23.1'),
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    paddingTop: hp('9.5'),
    paddingLeft: wp('6'),
  },
  backRightBtnRight: {
    backgroundColor: '#1877F2',
    flex: 1,
    height: Platform.OS == 'ios' ? hp('19.2') : hp('23.1'),
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'flex-end',
    paddingTop: hp('9.5'),
    paddingRight: wp('6'),
  },
  groupName: {
    fontSize: hp('2.3'),
    color: Colors.black,
    fontWeight: '600',
    marginBottom: hp('1'),
  },
  groupMember: {
    fontSize: hp('1.8'),
    color: Colors.gray,
  },
  groupActive: status => ({
    fontSize: hp('1.8'),
    color: status == 'Active' ? Colors.fadeGreen : Colors.primaryColor,
    // marginTop: hp('-.4'),
  }),
  groupDesc: {
    flex: 1,
    marginLeft: wp('3'),
  },
  activeCardStyle: {
    // flexDirection: 'row',
    // backgroundColor: Colors.avtiveCard,
    paddingHorizontal: wp('1'),
    paddingVertical: hp('.6'),
    marginBottom: hp('3'),
    borderRadius: 10,
    flex: 1,
  },
  activeCardMain: status => ({
    flex: 1,
    backgroundColor:
      status == 'Active' ? Colors.avtiveCard : Colors.inavtiveCard,
    paddingHorizontal: wp('1.5'),
    paddingVertical: hp('.6'),
    marginBottom: hp('3'),
    borderRadius: 8,
    // height: hp('22'),
    flexDirection: 'row',
    marginHorizontal: wp('3.5'),
  }),
  cardLeft: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: wp('3'),
    paddingTop: hp('1.5'),
  },
  TripBtn: {
    width: wp('27'),
    textAlign: 'center',
    height: hp('5'),
    justifyContent: 'center',
    marginHorizontal: wp('3'),
    marginBottom: hp('-1.5'),
    marginTop: hp('-1.2'),
  },
  TripBtnText: {
    fontWeight: '400',
  },
  letterSt: {
    color: Colors.white,
    fontSize: hp('3'),
    fontWeight: '700',
  },
  letterStyle: {
    borderRadius: Math.round(
      Dimensions.get('window').width + Dimensions.get('window').height,
    ),
    width: Dimensions.get('window').width * 0.13,
    height: Dimensions.get('window').width * 0.13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trachIcon: {
    width: wp('6'),
    resizeMode: 'contain',
  },
  editIcon: {
    width: wp('6'),
    resizeMode: 'contain',
  },
  loaderMain: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginVertical: hp('1.5'),
  },
  LoaderImage: {
    width: wp('15'),
    height: hp('7.5'),
    borderRadius: 50,
  },
  loaderInner: {
    marginLeft: wp('5'),
    marginRight: wp('18'),
  },
  loaderName: {
    width: wp('40'),
    height: hp('2'),
    marginTop: hp('1'),
  },
  loaderDes: {
    width: wp('30'),
    height: hp('1'),
    marginTop: hp('1'),
  },
  loaderBtn: {
    width: wp('30'),
    height: hp('4'),
    marginTop: hp('4'),
    marginLeft: wp('1'),
  },
  loaderBar: {
    width: wp('10'),
    height: hp('16'),
    borderRadius: 5,
  },
  refresh: {
    marginTop: hp('6'),
  },
  tabarTitle: {
    fontSize: hp('1.1'),
  },
  circleView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp('14'),
    marginTop: hp('-0.6'),
  },
  messageNumber: {
    color: Colors.primaryColor,
    fontSize: hp('1.5'),
  },
  groupLogo: {
    backgroundColor: 'red',
    width: Dimensions.get('window').width * 0.1,
    height: Dimensions.get('window').width * 0.1,
  },
  bottomModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  heading: {
    fontSize: hp('2.2'),
    fontWeight: '600',
    color: 'red',
    textAlign: 'center',
    alignSelf: 'center',
  },
  gText: {
    alignSelf: 'center',
    marginBottom: hp('2.3'),
  },
  profileText: {
    marginBottom: hp('1'),
    alignSelf: 'center',
    width: Dimensions.get('window').width * 0.18,
    height: Dimensions.get('window').width * 0.18,
  },
  creatorInfoMain: {
    flexDirection: 'row',
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
    backgroundColor: 'white',
    ...shadowStyleGlobal,
  },
  creatorProfile: {
    marginRight: wp('2.5'),
  },
  creatorName: {
    fontSize: hp('2'),
    fontWeight: '600',
    color: Colors.black,
    marginBottom: hp('0.2'),
    flex: 0.8,
  },
  creator: {
    flex: 0.3,
    alignItems: 'center',
    verticalAlign: 'middle',
    textAlign: 'right',
  },
  tripCreator: {
    fontSize: hp('1.8'),
    fontWeight: '400',
    color: Colors.black,
  },
  creatorInfo: {
    verticalAlign: 'middle',
    justifyContent: 'center',
    marginLeft: wp('2.5'),
  },
  locationArea: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flexWrap: 'wrap',
    // backgroundColor: 'yellow',
    marginBottom: hp('1'),
  },
  destinationArea: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flexWrap: 'wrap',
    // backgroundColor: 'yellow',
    // marginTop: hp('3'),
  },
  dotbar: {
    resizeMode: 'contain',
    // width: wp('12'),
    height: hp('6'),
    // maxHeight: hp('20'),
    // marginVertical: hp('-0.5'),
    alignSelf: 'flex-start',
    left: wp('-1.7'),
  },
  locationInfoMain: {
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
    backgroundColor: 'white',
    ...shadowStyleGlobal,
    // position: 'relative',
  },
  desImage: {
    resizeMode: 'contain',
    width: wp('11'),
    height: hp('5.5'),
    marginRight: wp('2.5'),
    alignSelf: 'flex-start',
  },
  locImage: {
    resizeMode: 'contain',
    width: wp('11'),
    height: hp('5.5'),
    marginRight: wp('2.5'),
    alignSelf: 'flex-start',
  },
  desText: {
    fontSize: hp('1.8'),
    fontWeight: '400',
    color: 'black',
    flex: 1,
    lineHeight: 22,
  },
  memberList: {
    flexDirection: 'row',
    verticalAlign: 'middle',
    alignItems: 'center',
    flex: 1,
  },
  memberText: {
    borderBottomColor: Colors.grayBorder,
    borderBottomWidth: 1,
    flex: 1,
    paddingBottom: hp('1.5'),
    marginBottom: hp('1.5'),
    marginTop: hp('2.7'),
    marginLeft: wp('2.5'),
    flexDirection: 'row',
  },
  memberInfo: {
    flexDirection: 'row',
    border: 1,
    borderColor: Colors.grayBorder,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: hp('1'),
    paddingHorizontal: wp('3'),
    paddingVertical: hp('1.5'),
    height: 'auto',
    backgroundColor: 'white',
    ...shadowStyleGlobal,
  },
  LText: {
    // flex: 0.8,
    borderColor: Colors.themeColorDark,
    width: wp('75'),
    marginBottom: hp('2'),
    textAlignVertical: 'top',
    verticalAlign: 'top',
  },
  dotImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // marginVertical: hp('3'),
    // height: hp('6'),
    // backgroundColor: 'red',
  },
  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    width: wp('100'),
    height: hp('100'),
    // opacity: 0.67,
  },
  modalStyle: (keyBoard, Android) => ({
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    shadowColor: '#000000',
    shadowOffset: {
      width: 2,
      height: 10,
    },
    shadowOpacity: 3,
    shadowRadius: 7.68,
    elevation: 20,
    // flex: 1,
    justifyContent: 'flex-start',
    height: keyBoard && Android ? hp('50') : hp('87'),
    paddingHorizontal: wp('2'),
  }),
  closeIcon: {
    justifyContent: 'flex-end',
    alignSelf: 'flex-end',
    marginTop: hp('2'),
    marginRight: wp('1.5'),
  },
  editIcon: {
    width: wp('6'),
    height: hp('3'),
    resizeMode: 'contain',
  },
  editInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: Colors.grayBorder,
    border: 1,
    height: hp('6'),
    // marginVertical: hp('3.5'),
    // marginBottom: hp('3.5'),
    marginTop: hp('1'),
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: wp('3'),
  },
  eInput: {
    height: hp('6'),
    paddingHorizontal: wp('3'),
    color: Colors.black,
    flex: 1,
  },
  userImageStyle: {
    width: wp('6'),
    height: hp('6'),
  },
  addImageBtn: {
    position: 'absolute',
    left: wp('52'),
    top: hp('3'),
    // backgroundColor: 'red',
    zIndex: 1,
  },
  addImageIcon: {
    alignSelf: 'center',
    // position: 'absolute',
    // left: wp('50%'),
    // bottom: hp('5'),
    // zIndex: 999,
    width: wp('12'),
    height: hp('6'),
    resizeMode: 'contain',
  },
  memberHeadingView: {
    marginTop: hp('3'),
    marginBottom: hp('2'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  memberHeading: {
    fontWeight: 'bold',
    marginLeft: wp('1'),
    fontSize: hp('2.5'),
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  modalData: tripType => ({
    // height: tripType ? hp('40') : hp('30'),
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    shadowColor: '#000000',
    shadowOffset: {
      width: 2,
      height: 10,
    },
    shadowOpacity: 3,
    shadowRadius: 7.68,
    elevation: 20,
  }),
  SelectTripModal: {
    paddingHorizontal: wp('4'),
    marginTop: hp('2.5'),
  },
  mainInput: {
    paddingHorizontal: wp('4'),
  },
  input: {
    borderColor: Colors.grayBorder,
    border: 1,
    height: hp('6'),
    marginVertical: hp('2'),
    borderWidth: 1,
    borderRadius: 7,
    // paddingHorizontal: wp('3'),
    flex: 1,
    marginHorizontal: wp('3'),
  },
  inputArea: {
    flexDirection: 'row',
    // alignItems: 'center',
    // paddingTop: hp('6'),
    // backgroundColor: 'green',
  },
  inputLeftImg: {
    width: wp('10'),
    height: hp('5'),
    resizeMode: 'contain',
    marginTop: hp('2.5'),
  },
  inputRightImg: {
    width: wp('8'),
    height: hp('4'),
    resizeMode: 'contain',
    marginTop: hp('2.5'),
  },
  selectTrip: {
    fontWeight: '600',
    fontSize: hp('3'),
    color: Colors.primaryColor,
    marginBottom: hp('2'),
    textAlign: 'center',
  },
  memberPic: {
    width: Dimensions.get('window').width * 0.1,
    height: Dimensions.get('window').width * 0.1,
  },
  groupMembers: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('3'),
  },
  modalScroll: keyboardStatus => ({
    // position: 'relative',
    // height: hp('50'),
    maxHeight: keyboardStatus ? hp('30') : hp('65'),
  }),
  groupTitle: {
    fontSize: hp('1.8'),
    fontWeight: '600',
    marginLeft: wp('2'),
    flex: 1,
  },
  groupBtn: {
    marginTop: hp('1'),
    marginBottom: Platform.OS == 'ios' ? hp('4') : hp('1'),
  },
  searchinput: {
    fontSize: hp('2'),
    color: 'black',
    flex: 1,
  },
  searchMain: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    height: hp('6'),
    borderRadius: 10,
    borderColor: Colors.themeColorLight,
    paddingHorizontal: wp('1.8'),
    overflow: 'hidden',
    backgroundColor: Colors.white,
    marginBottom: hp('2'),
  },
  tickIcon: {
    resizeMode: 'contain',
    height: hp('3'),
    width: wp('5'),
  },
  firstLetterStyle: {
    width: Dimensions.get('window').width * 0.1,
    height: Dimensions.get('window').width * 0.1,
  },
  tripNameError: {
    color: 'red',
    // marginBottom: hp('3.5'),
    // marginTop: hp('0.5'),
    fontSize: hp('1.5'),
    marginLeft: wp('1'),
    marginVertical: hp('1'),
  },
});
